<#import "parts/common.ftlh" as c>

<@c.page>
    <h5>Здравствуй, гость!</h5>
    <div>Это мой Java проект под названием "Sticker World". Простое веб приложение микроблога. Используется Spring Framework, Maven, PostgreSQL, Bootstrap.</div><br />
    <h5>Hello, guest!</h5>
    <div>This is my Java project "Sticker World". Simple microblog webapp. Using Spring Framework, Maven, PostgreSQL, Bootstrap.</div>
</@c.page>